<div id="documentspanel">
   <?php  
        $this->beginWidget('zii.widgets.CPortlet', array(
             )); 
                //echo Chtml::link('sdfsdf',Yii::app()->createUrl('helptree/DownloadFile',array('filename'=>'2260358673_keyboard_1.jpg')), array('img'=>'src=; alt="альтернативный текст">'));
                if ($model->doc != '')
                    echo Chtml::link(CHtml::image('/assets/doc.png','doc icon is missing',array('width'=>'40px','height'=>'40px','title'=>'Скачать в формате Word')),Yii::app()->createUrl('helptree/DownloadFile',array('filename'=>$model->doc)));
                if ($model->pdf != '')
                    echo Chtml::link(CHtml::image('/assets/pdf.png','pdf icon is missing',array('width'=>'40px','height'=>'40px','title'=>'Скачать в формате PDF')),Yii::app()->createUrl('helptree/DownloadFile',array('filename'=>$model->pdf)));  
                if (Yii::app()->user->checkAccess('moderator'))
                    echo Chtml::link(CHtml::image('/assets/edit.png','edit icon is missing',array('title'=>'Изменить материал')), Yii::app()->createUrl('helptree/update', array('id'=>$model->id)));
                //echo Chtml::link(CHtml::image('/assets/doc.gif','doc icon is missing',array('width'=>'40px','height'=>'40px')),Yii::app()->createUrl('helptree/delete',array('id'=>$model->id)));
                if (Yii::app()->user->checkAccess('moderator'))
                    echo Chtml::link(CHtml::image('/assets/question.png','question icon is missing',array('title'=>'Изменить вопросы самоконтроля')), Yii::app()->createUrl('helptree/manageQuestions', array('id'=>$model->id)));
                $this->widget('ext.mPrint.mPrint', array(
                    'title' => $model->title,          //the title of the document. Defaults to the HTML title
                    'tooltip' => 'Печать',        //tooltip message of the print icon. Defaults to 'print'
                    'text' => '',   //text which will appear beside the print icon. Defaults to NULL
                    'element' => '#HelptreeViewContent',        //the element to be printed.
                    'exceptions' => array(       //the element/s which will be ignored
                        '.summary',
                        '.search-form'
                    ),
                    'publishCss' => true,       //publish the CSS for the whole page?
                    //'visible' => Yii::app()->user->checkAccess('print'),  //should this be visible to the current user?
                    'alt' => 'print',       //text which will appear if image can't be loaded
                    'debug' => false,            //enable the debugger to see what you will get
                    //'id' => 'documentspanel'         //id of the print link
                ));
                
               /* $this->widget('zii.widgets.jui.CJuiButton', array(
                    'name'=>'buttonchangesize',
                    'caption'=>'Изменить размер',
                    //'value'=>'abc',
                    'htmlOptions'=>array(
                        //'style'=>'height:40px; width:250px',
                        'class'=>'btn btn-primary btn-large'
                        ),
                    'onclick'=>'js:changeSize()',
                    )
                );*/
        $this->endWidget(); 
               
        ?>
</div>
<div id="HelptreeTitle">
<h5><?php echo $model->title; echo '<div class="toolbox"><a id="wideView" class="fix" href="#" title="Свернуть/развернуть"></a></div>';?></h5>
</div>

<div id="HelptreeViewContent" class='fix'>
    
<?php 
    if ($model->htmlfield != '')
        echo $model->htmlfield;
    
    if ($model->img != '')
        echo Chtml::link(
                CHtml::image('/storage/'.$model->img,'Изображение недоступно!',array(
                    'style'=>'class: imagepreview',
                    )
                ),'/storage/'.$model->img,array(
                        'rel'=>'lightbox',
                        'title'=>$model->img,
                        )
                );
    
    if ($model->video != '')
    {
        $this->widget('ext.jwplayer.Jwplayer',array(
                'width'=>600,
                'height'=>360,
                'id'=>'HelptreeViewVideo',
                'file'=>'/storage/video/'.$model->video, // the file of the player, if null we use demo file of jwplayer
                //'image'=>'/assets/doc.jpg', // the thumbnail image of the player, if null we use demo image of jwplayer
                'options'=>array(
                    'controlbar'=>'bottom'
                )
            ));
           /* $this->widget('application.extensions.videojs.EVideoJS', array(
                'options' => array(
                    // Unique identifier, is autogenerated by default, useful for jQuery integrations.
                    'id' => false,
                    // Video and poster width in pixels
                    'width' => 320,
                    // Video and poster height in pixels
                    'height' => 240,
                    // Poster image absolute URL
                    'poster' => false,
                    // Absolute URL of the video in MP4 format
                    'video_mp4' => 'http://primus_yii2/storage/video/Dean DiMarzo Band - Bright Size Life (Pat Metheny).mp4',
                    // Absolute URL of the video in OGV format
                    'video_ogv' => false,
                    // Absolute URL of the video in WebM format
                    'video_webm' => false,
                    // Use Flash fallback player ?
                    'flash_fallback' => true,
                    // Address of custom Flash player to use as fallback
                    'flash_player' => 'flowplayer-3.2.1.swf',
                    // Show controls ?
                    'controls' => true,
                    // Preload video content ?
                    'preload' => true,
                    // Autostart the playback ?
                    'autoplay' => false,
                    // Show VideoJS support link ?
                    'support' => true,
                    // Show video download links ?
                    'download' => true,
                ),
            ));*/
        
           /* $this->widget('ext.bmvmediaplayer.BmvMediaPlayer', array(
                'src'=>'http://primus_yii2/storage/video/Dean DiMarzo Band - Bright Size Life (Pat Metheny).mp4',
                'fullScreen' =>true,
                'autoSize'=>true,
                'balance'=>1,
                'displaySize'=>1,
                'mute'=>false, // true or false
                'width'=>910,  // set your width as your requirement
                'height'=>700, 
                'playCount'=>0,
                'rate'=>1.0,
                'showAudioControls' =>true, // true or false
                'showControl'=>true, // true or false
                'showControl'=>true, // true or false
                'showDisplay'=>true, // true or false
                'showStatusBar'=>true, // true or false
                'showTracker'=>true, // true or false
                'stretchToFit'=>true, // true or false
                'transparentAtStart'=>true, // true or false
                'volume'=>100 // set volume as your requirement



            )); */
            
           /* $this->widget('application.extensions.smp.StrobeMediaPlayback',array(
                     'src'=>'http://primus_yii2/storage/video/'.$model->video,//'/storage/video/'.$model->video, //OR
                      //optional playlist:   
                      'playlistLinks'=>array(                                       
                                                             ),
                      'width'=>'600',
                      'height'=>'360',
                      'allowFullScreen'=>'true'    //default is true                            
            ));*/
    }
?>


</div>

<?php 
    if (Helpquestion::model()->findByAttributes(array('help_id'=>$model->id)))
    {
        $this->widget('zii.widgets.jui.CJuiButton', array(
            'name'=>'buttonRuntest',
            'caption'=>'Пройти самоконтроль!',
            'buttonType'=>'link',
            'url'=>Yii::app()->createUrl('helptree/runtest', array('id'=>$model->id)),
            )
        );
        //echo Chtml::link('Пройти самоконтроль',Yii::app()->createUrl('helptree/runtest', array('id'=>$model->id)));
    }
    
    if (Helpquestion::model()->findByAttributes(array('help_id'=>$model->id)))
    {
        $this->widget('zii.widgets.jui.CJuiButton', array(
            'name'=>'buttonViewResults',
            'caption'=>'Показать результаты самоконтроля!',
            'buttonType'=>'link',
            'url'=>Yii::app()->createUrl('helptree/runtest', array('id'=>$model->id)),
            )
        );
        //echo Chtml::link('Пройти самоконтроль',Yii::app()->createUrl('helptree/runtest', array('id'=>$model->id)));
    }
?>

<script>
        $(document).ready(function() {
            $("#wideView").click(function() {
                $("#HelptreeViewContent").toggleClass("fix");
                $(this).toggleClass("fix");
            });
        });
</script>

<!--
<script type="text/javascript" >

$(document).ready(function() {

// При клике на миниатюру
$('.imagepreview img').click(function()
{
// Берем свойство SRC миниатюры
// (можно картинку положить в ссылку и брать значение href
// для того, чтобы не грузить большие картинки изначально
// а загружать сначало миниатюры и только при клике открывать
// большое изображение, что будет целесообразнее).
var imgSrc = $(this).attr("src");
// Задаем свойство SRC картинке, которая в скрытом диве.
$('#img_container img').attr({src: imgSrc});
// Показываем скрытый контейнер
$('#img_container').fadeIn('slow');
});
// По клику на большое изображение, скрываем его
$('#img_container').click(function()
{
$(this).fadeOut();
});

});

$('#documentspanel').click(function()
{
    (this).fadeOut('slow');
});

</script>
-->